#debug: true

# PROFILES
## dev | test | prod
spring: 
  profiles.active: dev
  
# IDENTITY (ContextIdApplicationContextInitializer)
spring.application.index: MyBatis.v1.1
spring.application.name: MyBatis Boot

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server: 
  port:  8090
  session-timeout:  30
  tomcat.max-threads:  50
  tomcat.uri-encoding:  UTF-8
  
# LOGGING
logging: 
  path: /var/log
  file: cptadmin.log
  level.com.cpt: INFO

## osspath
oss.endpoint: http://oss-cn-shanghai.aliyuncs.com
oss.accessKeyId: LTAILAkR3Yb9Qnpt
oss.accessKeySecret: cL34LxbVmvFVx4JSe18p3CNwFcTvT5
oss.bucketName: govadmin
oss.web.url: http://govadmin.oss-cn-shanghai.aliyuncs.com/
oss.path.file: gov/file

# REDIS (RedisProperties)
spring.redis.shiro.database: 3
spring.redis.database: 2
spring.redis.host: 127.0.0.1
spring.redis.pool.max-active: 8
spring.redis.pool.max-total: 50
spring.redis.pool.max-wait-millis: 15000
spring.redis.pool.test-on-borrow: true
spring.redis.pool.max-idle: 10
spring.redis.pool.max-wait: -1 
spring.redis.pool.min-idle: 0 
spring.redis.port: 6379 
spring.redis.timeout: 3000

#MYBATIS
mybatis.mapper-locations: classpath*:/com/cpt/mapper/**.xml
mybatis.configuration.map-underscore-to-camel-case: true
mybatis.configuration.use-generated-keys: true
mybatis.configuration.default-fetch-size: 100
mybatis.configuration.default-statement-timeout: 30

#DATASOURCE
spring.datasource.continueOnError: true

spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
spring.datasource.url: jdbc:mysql://localhost:3306/gov
spring.datasource.username: root
spring.datasource.password: 123
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
spring.datasource.maxWait: 60000
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.validationQuery: SELECT 1
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.filters: stat
spring.datasource.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# VELOCITY TEMPLATES (VelocityAutoConfiguration)
spring.velocity.allow-request-override: false
spring.velocity.allow-session-override: false
spring.velocity.cache: true
spring.velocity.charset: UTF-8
spring.velocity.check-template-location: true
spring.velocity.content-type: text/html
spring.velocity.date-tool-attribute: date
spring.velocity.enabled: true
spring.velocity.expose-request-attributes: true
spring.velocity.expose-session-attributes: false
spring.velocity.expose-spring-macro-helpers: true
spring.velocity.number-tool-attribute: number
spring.velocity.prefer-file-system-access: true
spring.velocity.resource-loader-path: classpath:/templates/
spring.velocity.request-context-attribute: rc
spring.velocity.suffix: .vm
spring.velocity.toolbox-config-location: toolbox.xml

## server image
image.url: http\://172.16.121.201
server.imagepath: D:/images
server.imagepath.attachment: /attachment

---
spring:
  profiles: prod

# IDENTITY (ContextIdApplicationContextInitializer)
spring.application.index: MyBatis.v1.1
spring.application.name: MyBatis Boot

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server: 
  port:  8090
  session-timeout:  30
  tomcat.max-threads:  50
  tomcat.uri-encoding:  UTF-8
  
# LOGGING
logging: 
  path: /var/log
  file: cptadmin.log
  level.com.cpt: INFO

## osspath
oss.endpoint: http://oss-cn-shanghai.aliyuncs.com
oss.accessKeyId: LTAILAkR3Yb9Qnpt
oss.accessKeySecret: cL34LxbVmvFVx4JSe18p3CNwFcTvT5
oss.bucketName: govadmin
oss.web.url: http://govadmin.oss-cn-shanghai.aliyuncs.com/
oss.path.file: gov/file
multipart.maxFileSize: 10MB
multipart.maxRequestSize: 100MB
# REDIS (RedisProperties)
spring.redis.shiro.database: 5
spring.redis.database: 4
spring.redis.host: r-bp11b90f462293a4.redis.rds.aliyuncs.com
spring.redis.password: Cpt123456
spring.redis.pool.max-active: 8
spring.redis.pool.max-total: 50
spring.redis.pool.max-wait-millis: 15000
spring.redis.pool.test-on-borrow: true
spring.redis.pool.max-idle: 10
spring.redis.pool.max-wait: -1 
spring.redis.pool.min-idle: 0 
spring.redis.port: 6379 
spring.redis.timeout: 3000

#MYBATIS
mybatis.mapper-locations: classpath*:/com/cpt/mapper/**.xml
mybatis.configuration.map-underscore-to-camel-case: true
mybatis.configuration.use-generated-keys: true
mybatis.configuration.default-fetch-size: 100
mybatis.configuration.default-statement-timeout: 30

#DATASOURCE
spring.datasource.continueOnError: true

spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
spring.datasource.url: jdbc:mysql://rm-bp14p99h6n5y91744o.mysql.rds.aliyuncs.com:3306/gov
spring.datasource.username: cpt
spring.datasource.password: Cpt123456
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
spring.datasource.maxWait: 60000
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.validationQuery: SELECT 1
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.poolPreparedStatements: true
spring.datasource.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.filters: stat
spring.datasource.connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# VELOCITY TEMPLATES (VelocityAutoConfiguration)
spring.velocity.allow-request-override: false
spring.velocity.allow-session-override: false
spring.velocity.cache: true
spring.velocity.charset: UTF-8
spring.velocity.check-template-location: true
spring.velocity.content-type: text/html
spring.velocity.date-tool-attribute: date
spring.velocity.enabled: true
spring.velocity.expose-request-attributes: true
spring.velocity.expose-session-attributes: false
spring.velocity.expose-spring-macro-helpers: true
spring.velocity.number-tool-attribute: number
spring.velocity.prefer-file-system-access: true
spring.velocity.resource-loader-path: classpath:/templates/
spring.velocity.request-context-attribute: rc
spring.velocity.suffix: .vm
spring.velocity.toolbox-config-location: toolbox.xml

## server image
image.url: http\://172.16.121.201
server.imagepath: images
server.imagepath.attachment: /attachment